// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/newsletter": {
    params: {};
  };
  "/robots.txt": {
    params: {};
  };
  "/api/contact": {
    params: {};
  };
  "/:locale?": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/blogs/:blogHandle/:articleHandle": {
    params: {
      "locale"?: string;
      "blogHandle": string;
      "articleHandle": string;
    };
  };
  "/:locale?/sitemap/:type/:page.xml": {
    params: {
      "locale"?: string;
      "type": string;
      "page": string;
    };
  };
  "/:locale?/blogs/:blogHandle": {
    params: {
      "locale"?: string;
      "blogHandle": string;
    };
  };
  "/:locale?/pages/terms-of-service": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/pages/privacy-policy": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/collections/:handle": {
    params: {
      "locale"?: string;
      "handle": string;
    };
  };
  "/:locale?/account/authorize": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/collections": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/policies/:handle": {
    params: {
      "locale"?: string;
      "handle": string;
    };
  };
  "/:locale?/products/:handle": {
    params: {
      "locale"?: string;
      "handle": string;
    };
  };
  "/:locale?/account/logout": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/collections/all": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/policies": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/account/login": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/discount/:code": {
    params: {
      "locale"?: string;
      "code": string;
    };
  };
  "/:locale?/pages/shipping": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/pages/:handle": {
    params: {
      "locale"?: string;
      "handle": string;
    };
  };
  "/:locale?/pages/contact": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/pages/returns": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/sitemap.xml": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/blogs": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/pages/faq": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/account": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/account/orders": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/account/orders/:id": {
    params: {
      "locale"?: string;
      "id": string;
    };
  };
  "/:locale?/account/addresses": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/account/profile": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/account/*": {
    params: {
      "locale"?: string;
      "*": string;
    };
  };
  "/:locale?/search": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/cart": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/cart/:lines": {
    params: {
      "locale"?: string;
      "lines": string;
    };
  };
  "/:locale?/*": {
    params: {
      "locale"?: string;
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/newsletter" | "/robots.txt" | "/api/contact" | "/:locale?" | "/:locale?/blogs/:blogHandle/:articleHandle" | "/:locale?/sitemap/:type/:page.xml" | "/:locale?/blogs/:blogHandle" | "/:locale?/pages/terms-of-service" | "/:locale?/pages/privacy-policy" | "/:locale?/collections/:handle" | "/:locale?/account/authorize" | "/:locale?/collections" | "/:locale?/policies/:handle" | "/:locale?/products/:handle" | "/:locale?/account/logout" | "/:locale?/collections/all" | "/:locale?/policies" | "/:locale?/account/login" | "/:locale?/discount/:code" | "/:locale?/pages/shipping" | "/:locale?/pages/:handle" | "/:locale?/pages/contact" | "/:locale?/pages/returns" | "/:locale?/sitemap.xml" | "/:locale?/blogs" | "/:locale?/pages/faq" | "/:locale?/account" | "/:locale?/account/orders" | "/:locale?/account/orders/:id" | "/:locale?/account/addresses" | "/:locale?/account/profile" | "/:locale?/account/*" | "/:locale?/search" | "/:locale?/cart" | "/:locale?/cart/:lines" | "/:locale?/*";
  };
  "routes/api.newsletter.ts": {
    id: "routes/api.newsletter";
    page: "/api/newsletter";
  };
  "routes/[robots.txt].tsx": {
    id: "routes/[robots.txt]";
    page: "/robots.txt";
  };
  "routes/api.contact.ts": {
    id: "routes/api.contact";
    page: "/api/contact";
  };
  "routes/($locale).tsx": {
    id: "routes/($locale)";
    page: "/:locale?" | "/:locale?/blogs/:blogHandle/:articleHandle" | "/:locale?/sitemap/:type/:page.xml" | "/:locale?/blogs/:blogHandle" | "/:locale?/pages/terms-of-service" | "/:locale?/pages/privacy-policy" | "/:locale?/collections/:handle" | "/:locale?/account/authorize" | "/:locale?/collections" | "/:locale?/policies/:handle" | "/:locale?/products/:handle" | "/:locale?/account/logout" | "/:locale?/collections/all" | "/:locale?/policies" | "/:locale?/account/login" | "/:locale?/discount/:code" | "/:locale?/pages/shipping" | "/:locale?/pages/:handle" | "/:locale?/pages/contact" | "/:locale?/pages/returns" | "/:locale?/sitemap.xml" | "/:locale?/blogs" | "/:locale?/pages/faq" | "/:locale?/account" | "/:locale?/account/orders" | "/:locale?/account/orders/:id" | "/:locale?/account/addresses" | "/:locale?/account/profile" | "/:locale?/account/*" | "/:locale?/search" | "/:locale?/cart" | "/:locale?/cart/:lines" | "/:locale?/*";
  };
  "routes/($locale).blogs.$blogHandle.$articleHandle.tsx": {
    id: "routes/($locale).blogs.$blogHandle.$articleHandle";
    page: "/:locale?/blogs/:blogHandle/:articleHandle";
  };
  "routes/($locale).sitemap.$type.$page[.xml].tsx": {
    id: "routes/($locale).sitemap.$type.$page[.xml]";
    page: "/:locale?/sitemap/:type/:page.xml";
  };
  "routes/($locale).blogs.$blogHandle._index.tsx": {
    id: "routes/($locale).blogs.$blogHandle._index";
    page: "/:locale?/blogs/:blogHandle";
  };
  "routes/($locale).pages.terms-of-service.tsx": {
    id: "routes/($locale).pages.terms-of-service";
    page: "/:locale?/pages/terms-of-service";
  };
  "routes/($locale).pages.privacy-policy.tsx": {
    id: "routes/($locale).pages.privacy-policy";
    page: "/:locale?/pages/privacy-policy";
  };
  "routes/($locale).collections.$handle.tsx": {
    id: "routes/($locale).collections.$handle";
    page: "/:locale?/collections/:handle";
  };
  "routes/($locale).account_.authorize.tsx": {
    id: "routes/($locale).account_.authorize";
    page: "/:locale?/account/authorize";
  };
  "routes/($locale).collections._index.tsx": {
    id: "routes/($locale).collections._index";
    page: "/:locale?/collections";
  };
  "routes/($locale).policies.$handle.tsx": {
    id: "routes/($locale).policies.$handle";
    page: "/:locale?/policies/:handle";
  };
  "routes/($locale).products.$handle.tsx": {
    id: "routes/($locale).products.$handle";
    page: "/:locale?/products/:handle";
  };
  "routes/($locale).account_.logout.tsx": {
    id: "routes/($locale).account_.logout";
    page: "/:locale?/account/logout";
  };
  "routes/($locale).collections.all.tsx": {
    id: "routes/($locale).collections.all";
    page: "/:locale?/collections/all";
  };
  "routes/($locale).policies._index.tsx": {
    id: "routes/($locale).policies._index";
    page: "/:locale?/policies";
  };
  "routes/($locale).account_.login.tsx": {
    id: "routes/($locale).account_.login";
    page: "/:locale?/account/login";
  };
  "routes/($locale).discount.$code.tsx": {
    id: "routes/($locale).discount.$code";
    page: "/:locale?/discount/:code";
  };
  "routes/($locale).pages.shipping.tsx": {
    id: "routes/($locale).pages.shipping";
    page: "/:locale?/pages/shipping";
  };
  "routes/($locale).pages.$handle.tsx": {
    id: "routes/($locale).pages.$handle";
    page: "/:locale?/pages/:handle";
  };
  "routes/($locale).pages.contact.tsx": {
    id: "routes/($locale).pages.contact";
    page: "/:locale?/pages/contact";
  };
  "routes/($locale).pages.returns.tsx": {
    id: "routes/($locale).pages.returns";
    page: "/:locale?/pages/returns";
  };
  "routes/($locale).[sitemap.xml].tsx": {
    id: "routes/($locale).[sitemap.xml]";
    page: "/:locale?/sitemap.xml";
  };
  "routes/($locale).blogs._index.tsx": {
    id: "routes/($locale).blogs._index";
    page: "/:locale?/blogs";
  };
  "routes/($locale).pages.faq.tsx": {
    id: "routes/($locale).pages.faq";
    page: "/:locale?/pages/faq";
  };
  "routes/($locale).account.tsx": {
    id: "routes/($locale).account";
    page: "/:locale?/account" | "/:locale?/account/orders" | "/:locale?/account/orders/:id" | "/:locale?/account/addresses" | "/:locale?/account/profile" | "/:locale?/account/*";
  };
  "routes/($locale).account.orders._index.tsx": {
    id: "routes/($locale).account.orders._index";
    page: "/:locale?/account/orders";
  };
  "routes/($locale).account.orders.$id.tsx": {
    id: "routes/($locale).account.orders.$id";
    page: "/:locale?/account/orders/:id";
  };
  "routes/($locale).account.addresses.tsx": {
    id: "routes/($locale).account.addresses";
    page: "/:locale?/account/addresses";
  };
  "routes/($locale).account.profile.tsx": {
    id: "routes/($locale).account.profile";
    page: "/:locale?/account/profile";
  };
  "routes/($locale).account._index.tsx": {
    id: "routes/($locale).account._index";
    page: "/:locale?/account";
  };
  "routes/($locale).account.$.tsx": {
    id: "routes/($locale).account.$";
    page: "/:locale?/account/*";
  };
  "routes/($locale).search.tsx": {
    id: "routes/($locale).search";
    page: "/:locale?/search";
  };
  "routes/($locale)._index.tsx": {
    id: "routes/($locale)._index";
    page: "/:locale?";
  };
  "routes/($locale).cart.tsx": {
    id: "routes/($locale).cart";
    page: "/:locale?/cart" | "/:locale?/cart/:lines";
  };
  "routes/($locale).cart.$lines.tsx": {
    id: "routes/($locale).cart.$lines";
    page: "/:locale?/cart/:lines";
  };
  "routes/($locale).$.tsx": {
    id: "routes/($locale).$";
    page: "/:locale?/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/api.newsletter": typeof import("./app/routes/api.newsletter.ts");
  "routes/[robots.txt]": typeof import("./app/routes/[robots.txt].tsx");
  "routes/api.contact": typeof import("./app/routes/api.contact.ts");
  "routes/($locale)": typeof import("./app/routes/($locale).tsx");
  "routes/($locale).blogs.$blogHandle.$articleHandle": typeof import("./app/routes/($locale).blogs.$blogHandle.$articleHandle.tsx");
  "routes/($locale).sitemap.$type.$page[.xml]": typeof import("./app/routes/($locale).sitemap.$type.$page[.xml].tsx");
  "routes/($locale).blogs.$blogHandle._index": typeof import("./app/routes/($locale).blogs.$blogHandle._index.tsx");
  "routes/($locale).pages.terms-of-service": typeof import("./app/routes/($locale).pages.terms-of-service.tsx");
  "routes/($locale).pages.privacy-policy": typeof import("./app/routes/($locale).pages.privacy-policy.tsx");
  "routes/($locale).collections.$handle": typeof import("./app/routes/($locale).collections.$handle.tsx");
  "routes/($locale).account_.authorize": typeof import("./app/routes/($locale).account_.authorize.tsx");
  "routes/($locale).collections._index": typeof import("./app/routes/($locale).collections._index.tsx");
  "routes/($locale).policies.$handle": typeof import("./app/routes/($locale).policies.$handle.tsx");
  "routes/($locale).products.$handle": typeof import("./app/routes/($locale).products.$handle.tsx");
  "routes/($locale).account_.logout": typeof import("./app/routes/($locale).account_.logout.tsx");
  "routes/($locale).collections.all": typeof import("./app/routes/($locale).collections.all.tsx");
  "routes/($locale).policies._index": typeof import("./app/routes/($locale).policies._index.tsx");
  "routes/($locale).account_.login": typeof import("./app/routes/($locale).account_.login.tsx");
  "routes/($locale).discount.$code": typeof import("./app/routes/($locale).discount.$code.tsx");
  "routes/($locale).pages.shipping": typeof import("./app/routes/($locale).pages.shipping.tsx");
  "routes/($locale).pages.$handle": typeof import("./app/routes/($locale).pages.$handle.tsx");
  "routes/($locale).pages.contact": typeof import("./app/routes/($locale).pages.contact.tsx");
  "routes/($locale).pages.returns": typeof import("./app/routes/($locale).pages.returns.tsx");
  "routes/($locale).[sitemap.xml]": typeof import("./app/routes/($locale).[sitemap.xml].tsx");
  "routes/($locale).blogs._index": typeof import("./app/routes/($locale).blogs._index.tsx");
  "routes/($locale).pages.faq": typeof import("./app/routes/($locale).pages.faq.tsx");
  "routes/($locale).account": typeof import("./app/routes/($locale).account.tsx");
  "routes/($locale).account.orders._index": typeof import("./app/routes/($locale).account.orders._index.tsx");
  "routes/($locale).account.orders.$id": typeof import("./app/routes/($locale).account.orders.$id.tsx");
  "routes/($locale).account.addresses": typeof import("./app/routes/($locale).account.addresses.tsx");
  "routes/($locale).account.profile": typeof import("./app/routes/($locale).account.profile.tsx");
  "routes/($locale).account._index": typeof import("./app/routes/($locale).account._index.tsx");
  "routes/($locale).account.$": typeof import("./app/routes/($locale).account.$.tsx");
  "routes/($locale).search": typeof import("./app/routes/($locale).search.tsx");
  "routes/($locale)._index": typeof import("./app/routes/($locale)._index.tsx");
  "routes/($locale).cart": typeof import("./app/routes/($locale).cart.tsx");
  "routes/($locale).cart.$lines": typeof import("./app/routes/($locale).cart.$lines.tsx");
  "routes/($locale).$": typeof import("./app/routes/($locale).$.tsx");
};